# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
jenkins:
  Master:
    Image: $DOCKER_REGISTRY/nuxeo/webui-jenkinsx
    ImageTag: 0.0.1
  Servers:
    Global:
      EnvVars:
        PUBLIC_DOCKER_REGISTRY: packages.nuxeo.com:5000
  Agent:
    PodTemplates:
      Nodejs-Nuxeo:
        Name: nodejs-nuxeo
        # ServiceAccount: fooo
        Label: jenkins-nodejs-nuxeo
        DevPodPorts: 9229, 3000, 8080
        volumes:
        - type: Secret
          secretName: jenkins-docker-cfg
          mountPath: /home/jenkins/.docker
        EnvVars:
          JENKINS_URL: http://jenkins:8080
          GIT_COMMITTER_EMAIL: webui+jx-bot@nuxeo.com
          GIT_AUTHOR_EMAIL: webui+jx-bot@nuxeo.com
          GIT_AUTHOR_NAME: nuxeo-webui-jx-bot
          GIT_COMMITTER_NAME: nuxeo-webui-jx-bot
          XDG_CONFIG_HOME: /home/jenkins
          DOCKER_CONFIG: /home/jenkins/.docker/
          NPM_CONFIG_REGISTRY: http://nexus/repository/npmjs-all/
        ServiceAccount: jenkins
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
            RequestCpu: "100m"
            RequestMemory: "128Mi"
            Args: '${computer.jnlpmac} ${computer.name}'
          Nodejs:
            Image: gcr.io/jenkinsxio/builder-nodejs:0.1.815
            Privileged: true
            RequestCpu: "400m"
            RequestMemory: "512Mi"
            LimitCpu: "2"
            LimitMemory: "2048Mi"
            # You may want to change this to true while testing a new image
            # AlwaysPullImage: true
            Command: "/bin/sh -c"
            Args: "cat"
            Tty: true
      Maven-Nodejs-Nuxeo:
        Name: maven-nodejs-nuxeo
        # ServiceAccount: fooo
        Label: jenkins-maven-nodejs-nuxeo
        DevPodPorts: 9229, 3000, 8080, 5005
        volumes:
          - type: Secret
            secretName: jenkins-maven-settings
            mountPath: /root/.m2/
          - type: Secret
            secretName: jenkins-docker-cfg
            mountPath: /home/jenkins/.docker
          - type: Secret
            secretName: jenkins-release-gpg
            mountPath: /home/jenkins/.gnupg
        EnvVars:
          _JAVA_OPTIONS: '-XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m'
          JENKINS_URL: http://jenkins:8080
          GIT_COMMITTER_EMAIL: webui+jx-bot@nuxeo.com
          GIT_AUTHOR_EMAIL: webui+jx-bot@nuxeo.com
          GIT_AUTHOR_NAME: nuxeo-webui-jx-bot
          GIT_COMMITTER_NAME: nuxeo-webui-jx-bot
          XDG_CONFIG_HOME: /home/jenkins
          DOCKER_CONFIG: /home/jenkins/.docker/
          # lets disable the noisy download artifact logging messages
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          NPM_CONFIG_REGISTRY: http://nexus/repository/npmjs-all/
        ServiceAccount: jenkins
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.26-1-alpine
            RequestCpu: "100m"
            RequestMemory: "128Mi"
            Args: "${computer.jnlpmac} ${computer.name}"
          MavenNodejs:
            Image: gcr.io/jenkinsxio/builder-maven-nodejs:0.1.815
            Privileged: true
            # Bump request and limits for functional tests
            RequestCpu: "2"  
            RequestMemory: "4Gi"
            LimitCpu: "4"
            LimitMemory: "8Gi"
            # You may want to change this to true while testing a new image
            # AlwaysPullImage: true
            Command: "/bin/sh -c"
            Args: "cat"
            Tty: true

PipelineSecrets:
  NPMToken: $NPM_TOKEN
  DockerConfig: |-
    {
      "auths": {
        "packages.nuxeo.com:5000": {
          "auth": "$PUBLIC_DOCKER_REGISTRY_AUTH"
        }
      }
    }

nexus:
  persistence:
    size: 32Gi
